# Generated by Django 4.2.3 on 2023-08-14 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electro_app', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('email_ID', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pin_code', models.IntegerField()),
                ('request_Type', models.CharField(choices=[('--PLEASE CHOOSE A SERVICE--', '--Please choose a service--'), ('laptop', 'LAPTOP'), ('tv', 'TV'), ('smart phone', 'SMART PHONE'), ('wifi', 'WIFI'), ('ac', 'AC')], default=' ', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('connect', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
